### ISSUE TITLE
Any ideas about the location of config.json file and vocab.txt file?

### ISSUE THREAD

**Issue by JHnlp** [usmaann/BioALBERT#2]

**Comment by usmaann** [comment]
Hi, 
BioALBERT is trained on ALBERT. You need to use ALBERT "config.json", vocab files with saved check points......

https://github.com/google-research/albert

!python -m albert.run_classifier \
  --data_dir=....../euadr \
  --output_dir=....../euadr/large_p_m \
  --init_checkpoint=...../bioalbert_large_pubmed_mimic/model.ckpt-best \
  --albert_config_file=...../model/PUBMED_large/albert_config.json \
  --vocab_file=...../model/PUBMED_large/30k-clean.vocab \
  --spm_model_file=..../model/PUBMED_large/30k-clean.model \
  --do_train=True \
  --do_eval=True \
  --do_predict=True \
  --do_lower_case \
  --max_seq_length=128 \
  --task_name=gad \
  --warmup_step=320 \
  --learning_rate=3e-5 \
  --train_step=10000 \
  --save_checkpoints_steps=500 \
  --train_batch_size=32 \
  --tpu_name=$TPU_ADDRESS \
  --use_tpu=True
